main: main.go
	fyne-cross windows -arch=386
	fyne-cross windows -arch=amd64
	cp fyne-cross/bin/windows-amd64/док_и_серт.exe dnc.exe
	cp fyne-cross/bin/windows-386/док_и_серт.exe dnc1.exe
	rm -rf fyne-cross
	rm Icon.png
